In [2]:
import numpy as np

In [3]:
vector = np.arange(1, 11)
print("1. Одновимірний масив:", vector)

1. Одновимірний масив: [ 1  2  3  4  5  6  7  8  9 10]


In [4]:
matrix_zeros = np.zeros((3, 3))
print("\n2. Двовимірний масив (нулі):", matrix_zeros)


2. Двовимірний масив (нулі): [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
matrix_random_int = np.random.randint(1, 11, size=(5, 5))
print("\n3. Масив 5x5 з випадковими цілими числами:", matrix_random_int)


3. Масив 5x5 з випадковими цілими числами: [[ 2  1  4  3 10]
 [ 1  1  2  7  7]
 [ 3  8  6  6  1]
 [ 8  5 10  4  1]
 [ 5  1  1  8  7]]


In [6]:
matrix_random_float = np.random.rand(4, 4)
print("\n4. Масив 4x4 з випадковими дійсними числами:", matrix_random_float)


4. Масив 4x4 з випадковими дійсними числами: [[0.64324174 0.42313799 0.50823413 0.35354621]
 [0.01368994 0.95526215 0.82948308 0.29075988]
 [0.56061069 0.8738373  0.96672494 0.39058926]
 [0.33903065 0.30021349 0.05137391 0.12825617]]


In [7]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
print("\n5. Додавання:", addition_result)
print("   Віднімання:", subtraction_result)
print("   Множення:", multiplication_result)


5. Додавання: [ 8 14 12  9  7]
   Віднімання: [-6 -4 -6  7  3]
   Множення: [ 7 45 27  8 10]


In [8]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)
dot_product = np.dot(vector1, vector2)
print("\n6. Скалярний добуток двох векторів:", dot_product)


6. Скалярний добуток двох векторів: 1.819064022899469


In [9]:
matrix_2x2_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_2 = np.random.randint(1, 11, size=(2, 3))
matrix_multiply_result = np.dot(matrix_2x2_1, matrix_2x2_2)
print("\n7. Перемноження матриць 2x2 та 2x3:", matrix_multiply_result)


7. Перемноження матриць 2x2 та 2x3: [[117  96  51]
 [ 57  42  33]]


In [10]:
matrix_3x3 = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3)
print("\n8. Обернена матриця 3x3:", inverse_matrix)


8. Обернена матриця 3x3: [[ 0.37037037 -0.11111111 -0.03703704]
 [-0.16666667  0.          0.16666667]
 [-0.04938272  0.14814815 -0.0617284 ]]


In [11]:
matrix_4x4 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix_4x4)
print("\n9. Транспонована матриця 4x4:", transposed_matrix)


9. Транспонована матриця 4x4: [[0.44900363 0.86546212 0.14037335 0.63555107]
 [0.82294866 0.92462523 0.18588324 0.27034045]
 [0.05530257 0.35647359 0.38362775 0.86054247]
 [0.17920209 0.78411963 0.87592525 0.48837733]]


In [12]:
matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
result_matrix_vector_multiply = np.dot(matrix_3x4, vector_4)
print("\n10. Перемноження матриці 3x4 на вектор розміром 4:", result_matrix_vector_multiply)


10. Перемноження матриці 3x4 на вектор розміром 4: [115 121 126]


In [13]:
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
result_matrix_vector_multiply_2 = np.dot(matrix_2x3, vector_3)
print("\n11. Перемноження матриці 2x3 на вектор розміром 3:", result_matrix_vector_multiply_2)


11. Перемноження матриці 2x3 на вектор розміром 3: [0.83577797 0.16607278]


In [14]:
matrix_elementwise_multiply_1 = np.random.randint(1, 11, size=(2, 2))
matrix_elementwise_multiply_2 = np.random.randint(1, 11, size=(2, 2))
result_elementwise_multiply = np.multiply(matrix_elementwise_multiply_1, matrix_elementwise_multiply_2)
print("\n12. Поелементне множення двох матриць 2x2:", result_elementwise_multiply)


12. Поелементне множення двох матриць 2x2: [[63 15]
 [30 64]]


In [15]:
matrix_multiply_2x2_1 = np.random.randint(1, 11, size=(2, 2))
matrix_multiply_2x2_2 = np.random.randint(1, 11, size=(2, 2))
result_matrix_multiply = np.dot(matrix_multiply_2x2_1, matrix_multiply_2x2_2)
print("\n13. Матричне множення двох матриць 2x2:", result_matrix_multiply)


13. Матричне множення двох матриць 2x2: [[84 52]
 [95 52]]


In [16]:
matrix_5x5_sum = np.random.randint(1, 101, size=(5, 5))
sum_of_matrix_elements = np.sum(matrix_5x5_sum)
print("\n14. Сума елементів матриці 5x5:", sum_of_matrix_elements)


14. Сума елементів матриці 5x5: 1309


In [17]:
matrix_4x4_1 = np.random.randint(1, 11, size=(4, 4))
matrix_4x4_2 = np.random.randint(1, 11, size=(4, 4))
matrix_difference = np.subtract(matrix_4x4_1, matrix_4x4_2)
print("\n15. Різниця двох матриць 4x4:", matrix_difference)


15. Різниця двох матриць 4x4: [[ 0 -2 -4 -5]
 [-3 -3  6  0]
 [ 2 -1 -6 -1]
 [ 7 -1  4  3]]


In [18]:
matrix_3x3_sum = np.random.rand(3, 3)
vector_column_sum = np.sum(matrix_3x3_sum, axis=1)
print("\n16. Вектор-стовпчик з сумами елементів кожного рядка матриці 3x3:", vector_column_sum)


16. Вектор-стовпчик з сумами елементів кожного рядка матриці 3x3: [0.38141548 1.37210707 1.98066031]


In [19]:
matrix_3x4_squares = np.random.randint(1, 11, size=(3, 4))
matrix_squares = np.square(matrix_3x4_squares)
print("\n17. Матриця квадратів чисел з ініційальної матриці 3x4:", matrix_squares)


17. Матриця квадратів чисел з ініційальної матриці 3x4: [[49  4 49 64]
 [16 64 16 25]
 [ 9 49 36 25]]


In [20]:
vector_sqrt = np.random.randint(1, 51, size=4)
vector_sqrt_result = np.sqrt(vector_sqrt)
print("\n18. Вектор з квадратними коренями чисел:", vector_sqrt_result)


18. Вектор з квадратними коренями чисел: [1.73205081 7.07106781 6.4807407  5.09901951]
